### ISSUE TITLE
Android SDK Installer - Blank List

### ISSUE THREAD

**Issue by jaredev** [DelphiWorlds/Tools#1]
I used this tool a few months ago and it worked great. However today tried it and after pressing the Download button, the tools are installed but no Build Tools or Platforms are listed in the list boxes. Maybe the URL for the downloads has changed? Is Source Code available anywhere so I could take a look?

Thanks

**Comment by DelphiWorlds** [comment]
Sorry, I only just saw this issue now. Can you run Android SDK Installer again, and click the Select SDK button and select the folder that the SDK downloaded to? The folder should have a sub-folder called "tools". Once you click "Select Folder" in the select folder dialog, a progress dialog should appear "Reading SDK Package Lists". Does that appear at all?

**Comment by jaredev** [comment]
OK. I selected C:/Android, which has a 'tools' sub-folder. After that, yes, the dialog appears "Reading SDK Package Lists" briefly then closes but the Build Tools and Platforms list boxes remain empty.

**Comment by RobertZawadzki** [comment]
I have the same. Blank list :(

**Comment by DelphiWorlds** [comment]
Can you try the latest version and see if this is still an issue?

**Comment by DelphiWorlds** [comment]
Closed due to no response
